### ISSUE TITLE
Theme does not take effect

### ISSUE THREAD

**Issue by Cutuchiqueno** [elliotboyd/obsidian-traffic-lights#2]
Following the installation steps the theme is not applied. The css is in the vault folder and custom themes is turned on, anyway nothing changes.

Obsidian 0.7.3, on
Manjaro Linux

**Comment by elliotboyd** [comment]
Did you also open the vault in obsidian where you put in the css?

**Comment by Cutuchiqueno** [comment]
Figured it out. For some reason I downloaded the css file wraped up in HTML - no idea how this happened. Not it works. Thanks, it is a great them especially Andy's plugin that lets you horizontally stack your panes is great.
